version: '3.8'

services:
  mongo:
    image: mongo:6.0
    container_name: 'mongo'
    # environment:
    #   - MONGO_INITDB_DATABASE=customer
    #   - MONGO_INITDB_ROOT_USERNAME=root
    #   - MONGO_INITDB_ROOT_PASSWORD=root123
    #   - MONGO_REPLICA_SET_NAME=rs0
    command: ["--replSet", "rs0", "--noauth"]  
    healthcheck:
      test: test $$(echo "rs.initiate().ok || rs.status().ok" | mongo --quiet) -eq 1
      interval: 10s
      start_period: 30s
    restart: always
    volumes:
      - ./mongo-volume:$USER_DIR/software/localmongodb6
    #   - $PWD/.docker/mongo/mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh
    #   - $PWD/.docker/mongo/replica.key:$USER_DIR/software/mongo6/replica.key
    ports:
      - '27017-27019:27017-27019'